[workspace]
resolver = "2"
members = [
    "shared",
    "server",
    "uds_http_request",
    "wasm_macros",
    "wasm_shared"
]

[workspace.dependencies]
wasmi = "0.36.0"

[profile.dev]
incremental = true
